name: collapsible
description: A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
version: 6.1.0
#author: Alexander Ryzhov <aryzhov07@gmail.com>
#forked: Andrew Penhorwood - forked on 2025-03-28

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0